# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffeebreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=300)),
                ('endereco', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=13, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=13, max_digits=15)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
            ],
        ),
    ]
